task 4 - view a list of articles
edeharrison/nc-news pull request #1
Opened 2023-03-13 16:36 UTC by edeharrison

_What is an individual article card going to look like?
How can you display the information in an engaging and accessible way?
How are you going to arrange the articles on the screen - how will this change with screens of different size?_

I've only done basic layout styling so far. I'll do more to make it responsive / cover a11y issues / engaging later

2023-03-13 16:49 UTC, HannahBurks requested changes
Hey Ede, lovely work so far - just a couple additions/changes to make. Once done, please send another pull request 😃

2023-03-13 16:49 UTC, HannahBurks commented on src/components/Articles.jsx
> +      {/* <li>
Let's get rid of any console logs or commented out code :)

2023-03-13 16:49 UTC, HannahBurks commented on src/components/Articles.jsx
> +export default function Articles({ articles }) {
We should also have a loading state for the articles, so that if we are still awaiting the data it will display a loading message - just how we did the other day 😄

2023-03-13 16:49 UTC, HannahBurks commented on src/components/Articles.jsx
> +              <li>
Data isn’t loading right away, this is due to an error in console (list items should each have a unique key prop -  let's resolve this error)

2023-03-13 16:54 UTC, edeharrison commented on src/components/Articles.jsx
> +      {/* <li>
Ah yes, always forget that. Done

2023-03-13 17:02 UTC, edeharrison commented on src/components/Articles.jsx
> +export default function Articles({ articles }) {
Done

2023-03-13 17:02 UTC, edeharrison commented on src/components/Articles.jsx
> +              <li>
Done

2023-03-14 10:12 UTC, Slyose approved these changes
Looks great Ede!! Feel free to merge

2023-03-14 10:18 UTC, merged